name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-action:
    strategy:
      matrix:
        image:
          - ubuntu-latest
          - macos-latest

        # Test the 3 cases for version
        version:
          - edge
          - 6328c3d69f2bc0ae8a8b5903cb36fe4b46b702c4
          - 0.4.0
    name: ${{ matrix.image }}/${{ matrix.version }}
    runs-on: ${{ matrix.image }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run action
        id: test-action
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Check muon is installed
        id: output
        run: muon version
